#!/usr/bin/env bash
# Harden the Tauri-generated Android project so CI Gradle builds are
# deterministic.
#
# Two failure modes seen on GitHub runners (2026-10-07, `Build Android`):
#
#   1. `:buildSrc` resolved `org.jetbrains.kotlin:*2.0.21` from
#      `https://plugins.gradle.org/m2` ONLY and failed. `buildSrc` uses the
#      `kotlin-dsl` plugin, whose own artifacts resolve through
#      `pluginManagement` — the generated project declares no
#      `buildSrc/settings.gradle.kts`, so only the Gradle Plugin Portal is
#      consulted and a portal hiccup (or a version the portal mirror lacks)
#      fails the whole build. Fix: declare `gradlePluginPortal() +
#      mavenCentral() + google()` for `pluginManagement` (init script covers
#      the root build AND the nested `buildSrc` build) and guarantee the
#      `buildSrc` repositories contain all three.
#
#   2. Tauri picked the runner's preinstalled NDK (r30) even though
#      `NDK_HOME`/`ANDROID_NDK_HOME` pointed at the pinned r28 — the build
#      then compiled Rust against one NDK while Gradle wanted another.
#      This script does NOT touch the NDK (the workflow removes every NDK
#      except `$NDK_VERSION` before calling it); it only fixes repositories.
#
# Usage: bash scripts/android-gradle-harden.sh [gen/android-dir]
set -euo pipefail

cd "$(dirname "$0")/.."

ANDROID_DIR="${1:-src-tauri/gen/android}"
BUILDSRC_DIR="$ANDROID_DIR/buildSrc"
BUILDSRC_SETTINGS="$BUILDSRC_DIR/settings.gradle.kts"
BUILDSRC_BUILD="$BUILDSRC_DIR/build.gradle.kts"

if [ ! -d "$ANDROID_DIR" ]; then
  echo "::error::$ANDROID_DIR not found — run \`tauri android init\` first" >&2
  exit 1
fi

# ─── 1. buildSrc/settings.gradle.kts (plugin resolution for buildSrc) ──
# Without this file Gradle resolves `plugins { kotlin-dsl }` and its
# kotlin 2.x artifacts from the plugin portal alone.
if [ ! -f "$BUILDSRC_SETTINGS" ]; then
  cat > "$BUILDSRC_SETTINGS" <<'EOF'
// Generated by scripts/android-gradle-harden.sh (CI).
// buildSrc has its own settings build: without pluginManagement here,
// `kotlin-dsl` resolves org.jetbrains.kotlin:* from the plugin portal
// only, which flakes (see CI 2026-10-07). mavenCentral()/google() make
// the same artifacts resolvable from canonical Maven repos.
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}
EOF
  echo "wrote $BUILDSRC_SETTINGS"
else
  echo "$BUILDSRC_SETTINGS already exists — leaving it alone"
fi

# ─── 2. buildSrc/build.gradle.kts must list all three repos ─────────────
if [ -f "$BUILDSRC_BUILD" ]; then
  for repo in "gradlePluginPortal()" "mavenCentral()" "google()"; do
    if ! grep -q "$repo" "$BUILDSRC_BUILD"; then
      echo "::warning::$BUILDSRC_BUILD lacks $repo (template drift?) — patching" >&2
      # Insert into the first `repositories {` block (the buildSrc one).
      python3 - "$BUILDSRC_BUILD" "$repo" <<'PYEOF'
import sys
path, repo = sys.argv[1], sys.argv[2]
src = open(path).read()
marker = "repositories {"
idx = src.find(marker)
assert idx != -1, "no repositories block"
insert_at = idx + len(marker)
src = src[:insert_at] + "\n        " + repo + src[insert_at:]
open(path, "w").write(src)
PYEOF
    fi
  done
  echo "checked $BUILDSRC_BUILD repositories"
else
  echo "::warning::$BUILDSRC_BUILD not found — skipping repo check" >&2
fi

# ─── 3. Global init script (covers root build + buildSrc + app) ─────────
# Init scripts run for every Gradle build on the machine, including the
# nested buildSrc build, so this is the belt-and-braces layer even if the
# template drifts again.
INIT_DIR="${GRADLE_USER_HOME:-$HOME/.gradle}/init.d"
mkdir -p "$INIT_DIR"
cat > "$INIT_DIR/cybermanju-repos.gradle" <<'EOF'
// Generated by scripts/android-gradle-harden.sh (CI).
// Guarantees canonical Maven repos are available for plugin resolution
// (buildSrc kotlin-dsl) and for every project's buildscript/dependencies.
beforeSettings { settings ->
    settings.pluginManagement.repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}
allprojects {
    buildscript {
        repositories {
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
EOF
echo "wrote $INIT_DIR/cybermanju-repos.gradle"

# ─── 4. Retry flaky Maven fetches instead of failing the build ───────────
GRADLE_PROPS="$ANDROID_DIR/gradle.properties"
touch "$GRADLE_PROPS"
for prop in "org.gradle.internal.network.retry.maxAttempts=5" "org.gradle.internal.repository.max.tentatives=5"; do
  key="${prop%%=*}"
  if ! grep -q "^$key=" "$GRADLE_PROPS"; then
    echo "$prop" >> "$GRADLE_PROPS"
  fi
done
echo "hardened $GRADLE_PROPS with retry props"
echo "gradle repositories hardened"
